### PR TITLE
add pou, mls, medialitterature, postkarten, vitrocentre and change biz

### PR DESCRIPTION
**Pull request by danielasubotic**

### CODE REVIEW

**Review by BalduinLandolt — COMMENTED** [review]
Is there any way we could get the missing information for at least a part of those projects?

With each set of metadata, we're accumulating more "invalid" data, which is not ideal at all:
1. If we had a proper backend, that does data validation (which we hopefully someday do), that would be very unhappy.
2. Invalid data can't be converted to RDF, so it doesn't show up in Connectome.

In some files, it's missing quite a lot (medialitterature [12 properties], biz [8 properties], postkarten [12 properties]), so that probably can't be fixed on the spot.  
But in the others, we're not missing much:
- mls: `abstracts` in `datasets`
- pou: `url` in `project` (which should be the DaSCH landing page of the project)
- vitrocentre: `licenses` in `datasets`

(And just as a reminder, we're missing: 1 property in dokubib, 3 in beyondthetext, 12 in commode, 16 in decoso, 2 in delille, 16 in incunabula, 52 in lhtt, 20 in nietzsche, 1 in svg.)

**Comment by mrivoal** [comment]
Hi Balduin. 

Just a word about medialitterature. Since the project is still in a testing phase, I didn't bother to collect the project's metadata yet. I intend to do so just before the project goes live on a DaSCH production server. So I don't think this project is ready yet to publish its metadata.

**Review by BalduinLandolt — APPROVED** [review]
I guess we can merge it like that, and leave the housekeeping for later

**Comment by BalduinLandolt** [comment]
> Hi Balduin.
> 
> Just a word about medialitterature. Since the project is still in a testing phase, I didn't bother to collect the project's metadata yet. I intend to do so just before the project goes live on a DaSCH production server. So I don't think this project is ready yet to publish its metadata.

thanks for the info!

**Comment by BalduinLandolt** [comment]
@danielasubotic according to Marion's comment, we should probably remove `medialitterature` again, but once that's done, we're good to merge

**Comment by mpro7** [comment]
@BalduinLandolt reviewing PRs also make sure its title is correct. Here again there is no prafix, thus GH action didn't trigger the release.

**Pull request merged**
